
version: 2
updates:
  # Enable version updates for pip (Python)
  - package-ecosystem: "pip"
    # Look for a `requirements.txt` file in the root directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
  
  - package-ecosystem: "pip"
    # Look for a `requirements.txt` file in the docs directory
    directory: "/docs/"
    # Check for updates once a week
    schedule:
      interval: "weekly"