#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
SISCOMPLETER: Defines an object that helps for autocompletion of commands.
"""

__author__ = "Zenaro Stefano"

from prompt_toolkit.completion import NestedCompleter

try:
    from ._version import __version__  # noqa: F401
except ImportError:
    from _version import __version__  # noqa: F401

siscompleter = NestedCompleter.from_nested_dict({
    "act_map": None,
    "add_inverter": None,
    "alias": None,
    "astg_add_state": None,
    "astg_contract": None,
    "astg_current": None,
    "astg_encode": None,
    "astg_lockgraph": None,
    "astg_marking": None,
    "astg_persist": None,
    "astg_print_sg": None,
    "astg_print_stat": None,
    "astg_slow": None,
    "astg_state_min": None,
    "astg_stg_scr": None,
    "astg_syn": None,
    "astg_to_f": None,
    "astg_to_stg": None,
    "atpg": None,
    "bdsyn": None,
    "buffer_opt": None,
    "c_check": None,
    "c_opt": None,
    "chng_clock": None,
    "chng_name": None,
    "collapse": None,
    "constraints": None,
    "decomp": None,
    "echo": None,
    "eliminate": None,
    "env_seq_dc": None,
    "env_verify_fsm": None,
    "equiv_nets": None,
    "espresso": None,
    "extract_seq_dc": None,
    "factor": None,
    "fanout_alg": None,
    "fanout_param": None,
    "force_init_0": None,
    "free_dc": None,
    "full_simplify": None,
    "fx": None,
    "gcx": None,
    "gkx": None,
    "help": None,
    "history": None,
    "invert": None,
    "invert_io": None,
    "ite_map": None,
    "latch_output": None,
    "map": None,
    "one_hot": None,
    "phase": None,
    "power_estimate": None,
    "power_free_info": None,
    "power_print": None,
    "print": None,
    "print_altname": None,
    "print_clock": None,
    "print_delay": None,
    "print_factor": None,
    "print_gate": None,
    "print_io": None,
    "print_kernel": None,
    "print_latch": None,
    "print_level": None,
    "print_library": None,
    "print_map_stats": None,
    "print_state": None,
    "print_stats": None,
    "print_value": None,
    "quit": None,
    "read_astg": None,
    "read_blif": {
        "-a": None
    },
    "read_eqn": None,
    "read_kiss": None,
    "read_library": None,
    "read_pla": None,
    "read_slif": None,
    "red_removal": None,
    "reduce_depth": None,
    "remove_dep": None,
    "remove_latches": None,
    "replace": None,
    "reset_name": None,
    "resub": None,
    "retime": None,
    "save": None,
    "set": None,
    "set_delay": None,
    "set_state": None,
    "short_tests": None,
    "sim_verify": None,
    "simplify": None,
    "simulate": None,
    "source": None,
    "speed_up": None,
    "speedup_alg": None,
    "state_assign": None,
    "state_minimize": None,
    "stg_cover": None,
    "stg_extract": None,
    "stg_to_astg": None,
    "stg_to_network": None,
    "sweep": None,
    "tech_decomp": None,
    "time": None,
    "timeout": None,
    "unalias": None,
    "undo": None,
    "unset": None,
    "usage": None,
    "verify": None,
    "verify_fsm": None,
    "wd": None,
    "write_astg": None,
    "write_bdnet": None,
    "write_blif": None,
    "write_eqn": None,
    "write_kiss": None,
    "write_pds": None,
    "write_pla": None,
    "write_slif": None,
    "xl_absorb": None,
    "xl_ao": None,
    "xl_coll_ck": None,
    "xl_cover": None,
    "xl_decomp_two": None,
    "xl_imp": None,
    "xl_k_decomp": None,
    "xl_merge": None,
    "xl_part_coll": None,
    "xl_partition": None,
    "xl_rl": None,
    "xl_split": None
})
